#!/bin/bash

function usage() {
  echo "Usage: $(basename $0) <command> [options]"
  echo
  echo "Commands:"
  echo "  pull  - Pre-pull list of pre-defined images to kubernetes cluster"
  echo "  up    - Builds and deploys all images to kubernetes cluster"
  echo "  down  - Deletes all deployments"
  echo
  exit 1
}

function environment_login() {
  ./scripts/environment/login.sh
}

function environment_pull() {
  ./scripts/environment/pull.sh
}

function environment_up() {
  scripts/environment/up.sh
}

function environment_down {
  scripts/environment/down.sh
}

if [ $# -lt 1 ]; then
  usage
fi

command=$1
shift
case $command in
login)
  environment_login
  ;;
pull)
  environment_pull
  ;;
up)
  environment_up
  ;;
down)
  environment_down
  ;;
*)
  usage
  ;;
esac
