spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: controller
          ports:
            - containerPort: 5432
              hostPort: 5432
